# cachetag local autoconf macros.                        -*- Autoconf -*-
#
# This file is picked up automatically by aclocal (it always reads
# ./acinclude.m4 from the directory holding configure.ac) and automake
# distributes it as part of the configure dependencies.
#
# It deliberately does NOT live in m4/. That directory is listed in
# .gitignore and is populated by "autoreconf -i" with third-party libtool
# macros; the Docker test harness also excludes m4/ when it copies this
# source tree into the container. A tracked macro placed there would be
# invisible to both Git and the authoritative test harness.
#
# Contents:
#
#   CACHETAG_RELEASE_MANIFEST - optional --with-release-manifest=FILE gate

# CACHETAG_RELEASE_MANIFEST
# -------------------------
# Add the optional --with-release-manifest=FILE argument.
#
# cachetag declares "$ABI strict" in src/vmod_cachetag.vcc, so a built VMOD
# belongs to exactly one Vinyl Cache build, not to a release series. The
# packaging plan (devdocs/docs/20260724_1526_plan_binary-packaging-and-distribution.md,
# "Phase 0: define the release contract" -> "Configure-time checks") therefore
# requires configure to fail immediately when the package version or the ABI
# differs from the release compatibility manifest. Native packaging recipes
# under packaging/ are expected to pass
#
#     --with-release-manifest=<path-to>/vcache-packaging/registry/cohorts/<cohort-id>.yml
#
# so that a cohort rebuild against the wrong Vinyl development package cannot
# silently produce an unloadable artifact.
#
# When the argument is absent this macro emits no check and no output: an
# ordinary developer or harness build behaves exactly as before.
#
# The manifest is the restricted YAML subset documented in the sibling
# vcache-packaging repository's registry/README.md
# (two-space indentation, block mappings only, no tabs, no inline comments
# after a value), so three plain awk/sed extractions are enough and no YAML
# dependency is introduced into the build.
AC_DEFUN([CACHETAG_RELEASE_MANIFEST], [
	AC_ARG_WITH([release-manifest],
		AS_HELP_STRING([--with-release-manifest=FILE],
			[verify this build against a release cohort manifest;
			 used by packaging recipes, off by default]),
		[], [with_release_manifest=no])

	AS_IF([test "x$with_release_manifest" != xno],
		[_CACHETAG_RELEASE_MANIFEST_CHECK])
])

# _CACHETAG_RELEASE_MANIFEST_CHECK
# --------------------------------
# Compare the installed Vinyl Cache development surface and this package's
# version against the cohort manifest named by --with-release-manifest.
#
# Three manifest fields are consumed:
#
#   vinyl.strict_abi     - the exact strict VMOD ABI the cohort was built for
#   vinyl.version        - the Vinyl Cache upstream version of the cohort
#   cachetag.version     - must equal AC_PACKAGE_VERSION
#
# The authoritative strict ABI of an *installed* Vinyl Cache is the
# VMOD_ABI_Version string in ${pkgincludedir}/vmod_abi.h. That header is
# generated by Vinyl's include/generate.py as
#
#     #define VMOD_ABI_Version "<PACKAGE_STRING> <VCS revision>"
#
# and it is installed (include/Makefile.am lists vmod_abi.h under
# nobase_pkginclude_HEADERS). vmodtool.py bakes the same string into every
# VMOD's .abi field, and it is what Vinyl compares at load time for a strict
# VMOD, so it is the exact value a package must depend on. There is no
# pkg-config variable for it, and include/vcs_version.h - which holds the bare
# revision - is a noinst header that a development package does not ship, so
# vmod_abi.h is the only installed source of this value.
#
# The manifest records the trailing revision token (40 hex characters, as
# the registry schema specifies); a manifest value containing whitespace is
# instead compared against the complete VMOD_ABI_Version string.
#
# Every mismatch is collected and reported together, so one configure run
# tells a release engineer everything that is wrong.
AC_DEFUN([_CACHETAG_RELEASE_MANIFEST_CHECK], [
	AC_MSG_CHECKING([release manifest $with_release_manifest])

	cachetag_mf_file=$with_release_manifest
	cachetag_mf_awk=${AWK-awk}
	cachetag_mf_sed=${SED-sed}

	AS_IF([test "x$cachetag_mf_file" = xyes],
		[AC_MSG_RESULT([invalid])
		 AC_MSG_ERROR([--with-release-manifest requires a FILE argument, for example --with-release-manifest=../vcache-packaging/registry/cohorts/vinyl-9.0.0-<input-id>.yml])])

	AS_IF([test -f "$cachetag_mf_file"], [],
		[AC_MSG_RESULT([missing])
		 AC_MSG_ERROR([release manifest not found: $cachetag_mf_file])])

	dnl Extract one "section.key" scalar from the restricted YAML subset.
	dnl An empty section means a top-level key. Values may be plain, or
	dnl single- or double-quoted; quote characters are built with sprintf
	dnl so that the program itself stays single-quotable in the shell.
	[cachetag_mf_prog='
function unquote(s,   n, first) {
	sub(/[ ]+$/, "", s)
	sub(/\r$/, "", s)
	n = length(s)
	if (n < 2) return s
	first = substr(s, 1, 1)
	if (first != sprintf("%c", 34) && first != sprintf("%c", 39)) return s
	if (substr(s, n, 1) != first) return s
	return substr(s, 2, n - 2)
}
BEGIN { sect = "" }
/^[ ]*$/ { next }
/^[ ]*#/ { next }
/^[A-Za-z_][A-Za-z0-9_]*:/ {
	k = @S|@0
	sub(/:.*/, "", k)
	sect = k
	if (section == "" && k == key) {
		v = @S|@0
		sub(/^[^:]*:[ ]*/, "", v)
		print unquote(v)
		exit
	}
	next
}
/^  [A-Za-z_][A-Za-z0-9_]*:/ {
	if (sect != section) next
	k = @S|@0
	sub(/^  /, "", k)
	sub(/:.*/, "", k)
	if (k != key) next
	v = @S|@0
	sub(/^  [^:]*:[ ]*/, "", v)
	print unquote(v)
	exit
}
']

	cachetag_mf_status=`$cachetag_mf_awk -v section= -v key=status "$cachetag_mf_prog" "$cachetag_mf_file"`
	cachetag_mf_cohort=`$cachetag_mf_awk -v section= -v key=cohort "$cachetag_mf_prog" "$cachetag_mf_file"`
	cachetag_mf_vinyl_version=`$cachetag_mf_awk -v section=vinyl -v key=version "$cachetag_mf_prog" "$cachetag_mf_file"`
	cachetag_mf_strict_abi=`$cachetag_mf_awk -v section=vinyl -v key=strict_abi "$cachetag_mf_prog" "$cachetag_mf_file"`
	cachetag_mf_version=`$cachetag_mf_awk -v section=cachetag -v key=version "$cachetag_mf_prog" "$cachetag_mf_file"`

	dnl Read the strict ABI actually advertised by the installed Vinyl.
	cachetag_mf_pkgincludedir=`$PKG_CONFIG --variable=pkgincludedir vinylapi`
	cachetag_mf_abi_header=$cachetag_mf_pkgincludedir/vmod_abi.h
	AS_IF([test -r "$cachetag_mf_abi_header"], [],
		[AC_MSG_RESULT([failed])
		 AC_MSG_ERROR([cannot read $cachetag_mf_abi_header; the installed Vinyl Cache development files are incomplete, so the strict VMOD ABI cannot be verified])])

	[cachetag_mf_abi_string=`$cachetag_mf_sed -n 's/^[[:space:]]*#[[:space:]]*define[[:space:]]\{1,\}VMOD_ABI_Version[[:space:]]\{1,\}"\(.*\)".*$/\1/p' "$cachetag_mf_abi_header"`]
	AS_IF([test -n "$cachetag_mf_abi_string"], [],
		[AC_MSG_RESULT([failed])
		 AC_MSG_ERROR([no VMOD_ABI_Version definition found in $cachetag_mf_abi_header])])

	cachetag_mf_abi_id=`printf '%s\n' "$cachetag_mf_abi_string" | $cachetag_mf_awk '{print @S|@NF}'`

	dnl A manifest value with whitespace is a complete VMOD_ABI_Version
	dnl string; otherwise it is the trailing revision token.
	[case $cachetag_mf_strict_abi in
	*" "*|*"	"*) cachetag_mf_abi_actual=$cachetag_mf_abi_string ;;
	*) cachetag_mf_abi_actual=$cachetag_mf_abi_id ;;
	esac]

	cachetag_mf_errors=

	dnl Fail closed on a template manifest. Its digests, ABI string and
	dnl cohort input-id are reserved placeholders, so it must never be
	dnl accepted as evidence about a real build even by accident.
	AS_IF([test "x$cachetag_mf_status" = xtemplate],
		[cachetag_mf_errors="$cachetag_mf_errors
  - the manifest declares 'status: template'. A template manifest records
    placeholder digests and a reserved cohort input-id, and is never a valid
    description of a real build. Use a candidate or released cohort manifest."])

	AS_IF([test -n "$cachetag_mf_version"], [], [cachetag_mf_errors="$cachetag_mf_errors
  - the manifest does not define cachetag.version"])
	AS_IF([test -n "$cachetag_mf_vinyl_version"], [], [cachetag_mf_errors="$cachetag_mf_errors
  - the manifest does not define vinyl.version"])
	AS_IF([test -n "$cachetag_mf_strict_abi"], [], [cachetag_mf_errors="$cachetag_mf_errors
  - the manifest does not define vinyl.strict_abi"])

	AS_IF([test -n "$cachetag_mf_version" && test "x$cachetag_mf_version" != "x$PACKAGE_VERSION"],
		[cachetag_mf_errors="$cachetag_mf_errors
  - package version mismatch: this source tree is AC_PACKAGE_VERSION,
    the manifest requires cachetag.version $cachetag_mf_version"])

	AS_IF([test -n "$cachetag_mf_vinyl_version" && test "x$cachetag_mf_vinyl_version" != "x$VINYL_VERSION"],
		[cachetag_mf_errors="$cachetag_mf_errors
  - Vinyl Cache version mismatch: the installed development package reports
    $VINYL_VERSION, the manifest requires vinyl.version $cachetag_mf_vinyl_version"])

	AS_IF([test -n "$cachetag_mf_strict_abi" && test "x$cachetag_mf_strict_abi" != "x$cachetag_mf_abi_actual"],
		[cachetag_mf_errors="$cachetag_mf_errors
  - strict VMOD ABI mismatch: the installed Vinyl Cache advertises
    $cachetag_mf_abi_actual
    (VMOD_ABI_Version '$cachetag_mf_abi_string' from $cachetag_mf_abi_header),
    the manifest requires vinyl.strict_abi $cachetag_mf_strict_abi"])

	AS_IF([test -n "$cachetag_mf_errors"],
		[AC_MSG_RESULT([failed])
		 AC_MSG_ERROR([release manifest check failed for $cachetag_mf_file
  (cohort ${cachetag_mf_cohort:-unnamed}, status ${cachetag_mf_status:-unset})
$cachetag_mf_errors

cachetag is a strict-ABI VMOD: a binary built here is only loadable by the
exact Vinyl Cache build recorded in its cohort manifest. Rebuild against the
matching Vinyl Cache development package, or correct the manifest. Never relax
this check to make a package build succeed.])])

	AC_MSG_RESULT([ok (cohort ${cachetag_mf_cohort:-unnamed}, strict ABI $cachetag_mf_abi_actual)])
])
